---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  # security_group_ids: ["sg-1a2b3c4d"]
  security_group_ids: ["sg-4d135420"]
  region: us-east-1
  # availability_zone: b
  instance_type: t1.micro
  # associate_public_ip: true
  interface: dns

provisioner:
  name: chef_zero

transport:
  ssh_key: <%= ENV['AWS_KEYPATH'] %>
  connection_timeout: 10
  connection_retries: 5

platforms:
  - name: centos-6.5
    driver:
      image_id: ami-8997afe0
      # block_device_mappings:
      #   - ebs_device_name: /dev/sda1
      #     ebs_volume_type: standard
      #     ebs_virtual_name: test
      #     ebs_volume_size: 15
      #     ebs_delete_on_termination: true
    transport:
      username: root
  # - name: windows-2012r2
  # - name: windows-2008r2

suites:
  - name: default
    attributes:
