name 'skeleton'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures skeleton'
long_description 'Installs/Configures skeleton'
version '0.1.0'
